name: Myactions
env:
   APPLIC       : "My flask"
   Package_name : "Flask deploy ver ${{ github.sha}}"
on:
 push:
    branches:
       - main

jobs:
   my_testing:
      runs-on: ubuntu-latest

      steps:
      - name: Phint Hello message
        run: echo "Hello world from testing"
      - name: execute few commads
        run: |
           echo "Hello"
           echo "world"
           echo "${{env.APPLIC}}"
      - name: files in my repo
        run: ls -la
      - name: clon my repo
        uses: actions/checkout@v1
      - name: files in my repo now
        run: ls -la 
   
   my_deploy:
      runs-on: ubuntu-latest
      needs: [my_testing]
      env:
         var1: "This is job deploy variable 1"
         var2: "This is job deploy variable 2"
      steps:
      - name: Phint Hello message
        run: |
           echo "Hello world from deploy ver ${{env.Package_name}}"
           echo " variable1 = ${{env.var1}}"
           echo " variable2 = ${{env.var2}}"
           echo " variable3 = $Local"
        env:
         Local: "Very super local variable"
         
      - name: Can I'm use zip or python
        run: |
           zip --version
           python --version
